on:
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    outputs:
      upload_url: '${{ steps.create_release.outputs.upload_url }}'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        id: 'create_release'
        with:
          release_name: '${{ github.ref }}'
          tag_name: '${{ github.ref }}'
  build_web:
    needs:
      - create_release
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - run: |
          gpg --batch --decrypt --output "files/browser_client_secret.json" --passphrase "$PASSPHRASE" --yes "files/browser_client_secret.json.gpg"
          gpg --batch --decrypt --output "files/desktop_client_secret.json" --passphrase "$PASSPHRASE" --yes "files/desktop_client_secret.json.gpg"
          gpg --batch --decrypt --output "web/firebase-config.js" --passphrase "$PASSPHRASE" --yes "web/firebase-config.js.gpg"
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - uses: tnc1997/github-actions/actions/setup-flutter@setup-flutter_v1
        with:
          channel: 'dev'
      - run: flutter build web --no-sound-null-safety --web-renderer html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_PREVIEWS: 'hostingchannels'
        with:
          channelId: 'live'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIDAL_RUN_307407 }}'
          projectId: 'tidal-run-307407'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
  build_windows:
    needs:
      - create_release
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - run: |
          gpg --batch --decrypt --output "files/browser_client_secret.json" --passphrase "$PASSPHRASE" --yes "files/browser_client_secret.json.gpg"
          gpg --batch --decrypt --output "files/desktop_client_secret.json" --passphrase "$PASSPHRASE" --yes "files/desktop_client_secret.json.gpg"
          gpg --batch --decrypt --output "web/firebase-config.js" --passphrase "$PASSPHRASE" --yes "web/firebase-config.js.gpg"
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        shell: 'bash'
      - uses: tnc1997/github-actions/actions/setup-flutter@setup-flutter_v1
        with:
          channel: 'dev'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --no-sound-null-safety
      - run: Compress-Archive -DestinationPath Release.zip -Path build\windows\runner\Release
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          asset_content_type: 'application/zip'
          asset_name: 'windows.zip'
          asset_path: 'Release.zip'
          upload_url: '${{ needs.create_release.outputs.upload_url }}'
